import re

OVERRIDES = {
    "bolt":  "बोल्ट",
    "zara":  "ज़ारा",
    "nova":  "नोवा",
    "beep":  "बीप",
    "echo":  "एको",
    "mira":  "मीरा",
    "hi":        "हाय",
    "hello":     "हेलो",
    "hey":       "हे",
    "yes":       "यस",
    "no":        "नो",
    "ok":        "ओके",
    "okay":      "ओके",
    "bye":       "बाय",
    "please":    "प्लीज़",
    "sorry":     "सॉरी",
    "thanks":    "थैंक्स",
    "thank":     "थैंक",
    "great":     "ग्रेट",
    "good":      "गुड",
    "wow":       "वाओ",
    "yay":       "येय",
    "ball":      "बॉल",
    "cat":       "कैट",
    "dog":       "डॉग",
    "sun":       "सन",
    "tree":      "ट्री",
    "fish":      "फ़िश",
    "bird":      "बर्ड",
    "house":     "हाउस",
    "book":      "बुक",
    "cup":       "कप",
    "bed":       "बेड",
    "car":       "कार",
    "bus":       "बस",
    "egg":       "एग",
    "milk":      "मिल्क",
    "rice":      "राइस",
    "happy":     "हैपी",
    "sad":       "सैड",
    "run":       "रन",
    "jump":      "जम्प",
    "eat":       "ईट",
    "sleep":     "स्लीप",
    "play":      "प्ले",
    "sit":       "सिट",
    "red":       "रेड",
    "blue":      "ब्लू",
    "green":     "ग्रीन",
    "big":       "बिग",
    "small":     "स्मॉल",
    "one":       "वन",
    "two":       "टू",
    "three":     "थ्री",
    "say":       "से",
    "the":       "द",
    "word":      "वर्ड",
    "let":       "लेट",
    "us":        "हम",
    "am":        "हूँ",
    "i":         "मैं",
    "a":         "एक",
    "an":        "एक",
    "from":      "से",
    "your":      "तुम्हारा",
    "and":       "और",
    "to":        "को",
    "begin":     "शुरू",
    "ready":     "तैयार",
    "start":     "शुरू",
    "friend":    "दोस्त",
    "brave":     "बहादुर",
    "space":     "अंतरिक्ष",
    "robot":     "रोबोट",
    "alien":     "एलियन",
    "planet":    "ग्रह",
    "wise":      "समझदार",
    "calm":      "शांत",
    "guide":     "गाइड",
    "tiny":      "छोटा",
    "helper":    "सहायक",
    "fun":       "मज़ा",
    "learn":     "सीखें",
    "learning":  "सीखना",
    "together":  "साथ",
    "ancient":   "प्राचीन",
    "computer":  "कंप्यूटर",
    "distant":   "दूर",
    "galaxy":    "आकाशगंगा",
    "shall":     "क्या",
    "we":        "हम",
    "explore":   "खोजें",
    "words":     "शब्द",
    "today":     "आज",
    "underwater": "पानी के नीचे",
    "friendly":  "मिलनसार",
    "cheerful":  "खुशमिजाज़",
    "love":      "प्यार",
    "new":       "नया",
    "with":      "साथ",
    "you":       "तुम",
    "greetings": "नमस्ते",
    "zorb":      "ज़ॉर्ब",
    "beep":      "बीप",
    "let":       "चलो",
    "have":      "करें",
    "there":     "वहाँ",
    "shall":     "चलें",
    "explore":   "खोजें",
    "is":        "है",
    "my":        "मेरा",
    "name":      "नाम",
}

def to_devanagari(text: str) -> str:
    tokens = re.findall(r"[a-zA-Z]+|[^a-zA-Z]+", text)
    result = []
    for token in tokens:
        if re.match(r"[a-zA-Z]+", token):
            lower = token.lower()
            result.append(OVERRIDES.get(lower, token))
        else:
            result.append(token)
    return "".join(result)

if __name__ == "__main__":
    tests = [
        "Hi! I am Bolt, your brave space robot friend. Let us learn together!",
        "Hello! I am Zara, from planet Zorb. I love learning new words with you!",
        "Say the word ball.",
        "Say the word cup.",
        "Greetings. I am Nova, your calm and wise guide. Ready to begin?",
        "Beep beep! I am Beep, your tiny helper robot. Let us have fun learning!",
        "Hello there. I am Echo, an ancient computer from a distant galaxy. Shall we start?",
        "Hi friend! I am Mira, your friendly underwater robot. Let us explore words today!",
    ]
    for t in tests:
        print(f"IN:  {t}")
        print(f"OUT: {to_devanagari(t)}")
        print()
